apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rmq
spec:
  serviceName: rmq
  replicas: 3
  template:
    metadata:
      labels:
        app: rmq
    spec:
      containers:
      - name: rmq
        image: gcr.io/your-project/rabbitmq
        env:
          - name: CLUSTERED
            value: "true"
          - name: CLUSTER_WITH
            value: "rmq-0"
          # Needed for short rabbitmq host names
          - name: RABBITMQ_SERVICE_DOMAIN
            value: "rmq.default.svc.cluster.local"
        lifecycle:
          preStop:
            exec:
              command: ["rabbitmqctl", "stop"]
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 25672
        volumeMounts:
          - mountPath: /data
            name: rmq
  volumeClaimTemplates:
  - metadata:
      name: rmq
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
